#include "nsISupports.idl"
#include "nsIArray.idl"
#include "nsIObserver.idl"

[scriptable, function, uuid(a3fc75a0-7e82-4fb3-879b-a090f22d0dca)]
interface nsEveMarketDataHandler : nsISupports {
    void onData(in float price);
};

[scriptable, function, uuid(d020ad0d-ae3c-41c1-84de-28cd87855e82)]
interface nsEveMarketDataHandler2 : nsISupports {
    void onData(in nsISupports data);
};

[scriptable, uuid(30b3c4b3-f648-4f69-9189-6af0dd8b3e61)]
interface nsIEveMarketDataProviderService : nsIObserver {
    readonly attribute string name;
    readonly attribute nsIArray accepts;
    readonly attribute nsIArray provides;
    float getPriceForItem(in long typeID, in nsISupports params);
    boolean getPriceForItemAsync(in long typeID, in nsISupports params,
            in nsEveMarketDataHandler handler);
    void getPriceForItem2(in long typeID, in nsISupports params,
            [retval] out nsISupports retv);
    void getPriceForItemAsync2(in long typeID, in nsISupports params,
            in nsEveMarketDataHandler2 handler);
};

